Feature: CM 1065 Video Web Component
yml-org/fe-component-library pull request #17
Opened 2023-01-27 04:17 UTC by AswathiSYML

## Description
Implement video web component and corresponding stories.
### URLS

**JIRA Ticket:**
[CM-1065](https://ymedialabs.atlassian.net/browse/CM-1065)

**Local Dev:**
http://localhost:5173/

**Storybook Link:**
http://localhost:6006/?path=/story/videos--with-subtitles

### PR Checklist

Indicate that you have finished all requirements before requesting a review.
(place an 'x' in the box to mark as completed, add a strikethrough to any line that is not applicable).

Before requesting review:

- [x] Added reviewers
- [x] Added yourself as assignee
- [x] Checked in Chrome
- [x] Checked in Firefox
- [x] Checked in Safari
- [x] Checked in Edge

### Screenshots
[screen-capture (1).webm](https://user-images.githubusercontent.com/122965085/215007730-40c61b4c-6ce3-4cdd-be37-377819d4235f.webm)

### Additional Notes
Used videojs library inorder to implement this.
https://videojs.com/

2023-01-27 04:25 UTC, NileshSinhaYML requested changes

2023-01-27 04:25 UTC, NileshSinhaYML commented on packages/video/src/video/video.component.ts
> +      aspectRatio: this.videoStyle?.aspectRatio ?? '16:9',
Can we move the default aspect ration in a constant?

2023-01-27 04:25 UTC, NileshSinhaYML commented on packages/video/src/video/video.component.ts
> +        this.captions
Can we move this logic to a separate `protected` function to make this look cleaner and easy to understand

2023-01-27 04:25 UTC, NileshSinhaYML commented on packages/video/src/video/video.component.ts
> +      preload: 'auto',
Please update this to a property and give the default value as `auto` so that the user can control this as well

2023-01-27 04:25 UTC, NileshSinhaYML commented on packages/video/src/video/video.component.ts
> +  updated(changedProperties) {
Please update the type for `changedProperties`

2023-02-06 04:59 UTC, NileshSinhaYML approved these changes

2023-02-06 05:00 UTC, Ramyarnayak approved these changes

2023-02-06 05:00 UTC, merged