CM/1138 : flick-to-transition component
yml-org/fe-component-library pull request #30
Opened 2023-02-13 09:56 UTC by Ziyan7

## Description

Create an accelerator that can be used where flick to transition feature is required.

Smooth transition while swiping up and down through pages

Accept an array of object with order of pages/components

User should be able send component as slot 

It should work across multiple frameworks.

Overriding the tailwind 

Implement CSS :parts API

### URLS

**JIRA Ticket:**
[CM-1131](https://ymedialabs.atlassian.net/browse/CM-1131)

**Local Dev:**
http://localhost:5173/

**Storybook Link:**
http://localhost:6006/

### PR Checklist

Indicate that you have finished all requirements before requesting a review.
(place an 'x' in the box to mark as completed, add a strikethrough to any line that is not applicable).

Before requesting review:

- [x] Added reviewers
- [x] Added yourself as assignee
- [x] Checked in Chrome
- [ ] Checked in Firefox
- [ ] Checked in Safari
- [ ] Checked in Edge

### Screenshots

https://user-images.githubusercontent.com/68343846/218425902-483188e7-64e5-45d1-9668-d11502c15a92.mp4

https://user-images.githubusercontent.com/68343846/218425935-a359b5db-d9ec-4083-ab49-aaa2d10439f9.mp4

### Additional Notes

_replace this text with any additional notes, enter "N/A" if there are none_

2023-02-13 10:51 UTC, NileshSinhaYML requested changes
Clean up `packages/page-transition/src/transition/transition.component.ts`
It is not in a readable state and there are too many redundant conditions. Please optimise the code.

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/dist/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
Is the `dist` folder needed?

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/dist/assets/index.0720e34e.css
> +@charset "UTF-8";*,:before,:after{box-sizing:border-box;border-width:0;border-style:solid;border-color:#e5e7eb}:before,:after{--tw-content: ""}html{line-height:1.5;-webkit-text-size-adjust:100%;-moz-
Is the `dist` folder needed?

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/dist/assets/index.js
> +(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new Mutation
Is the `dist` folder needed?

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +  div : HTMLElement;
Can we give some meaningful names?
Names like `div` , `hiddenDiv` are very generic

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +    this.div.style.overflow = DivStyle.Overflow;
Can we write 

```
 this.div.style.position = DivStyle.Position;
    this.div.style.display = DivStyle.Display;
    this.div.style.overflow = DivStyle.Overflow;
    this.div.style.maxHeight = DivStyle.MaxHeight;
    this.div.style.maxWidth = DivStyle.MaxWidth;   
``` 




    as 
    

```
    this.div.style={  ...this.div.style,
                                position:DivStyle.Position,
                                display:DivStyle.Display,
                                overflow:DivStyle.Overflow,
                                maxHeight:DivStyle.MaxHeight,
                                maxWidth:DivStyle.MaxWidth
                                }
```

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +    axis === 'x'
Move this to a constant like `isXAsis= axis === 'x'` since it is used in multiple places

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +            eventName === EventType.TouchEvent
Move this to a constant

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +          ? (
Please simplify this.
Break this into smaller functions for better readability

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +        ) {
Can be simplified as 

` this.isScrolled=axis === 'x' ? this.div.scrollLeft === 0 : this.div.scrollTop === 0`

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +        this.swipedDirection === SwipeDirection.SwipedLeft
Can be simplified as 
`[SwipeDirection.SwipedLeft,SwipeDirection.SwipedUP].includes(this.swipedDirection)`

2023-02-13 10:51 UTC, NileshSinhaYML commented on packages/page-transition/src/transition/transition.component.ts
> +          ? (this.slotClass = 'animate__animated animate__fadeInRight')
```this.slotClass= `animate__animated ${this.scrollDirection === Direction.HORIZONTAL?'animate__fadeInRight':'animate__fadeInUp'}```
Do not use assignments within ternary

2023-02-13 11:57 UTC, Ziyan7 commented on packages/page-transition/src/transition/transition.component.ts
> +    this.div.style.overflow = DivStyle.Overflow;
it throws an error saying Cannot assign to 'style' because it is a read-only property

2023-02-14 06:09 UTC, NileshSinhaYML approved these changes

2023-02-14 06:13 UTC, AswathiSYML approved these changes

2023-02-14 06:14 UTC, merged